-- =============================================================================
-- AirCI Professional — trabajos asíncronos + resultados por vuelo + árboles
-- =============================================================================
-- Ejecutar en Supabase SQL Editor después de:
--   1) supabase-airci.sql
--   2) supabase-airci-canopy-results.sql
--
-- Es idempotente. Conserva los resultados legacy en trees_json.
-- =============================================================================

-- Un resultado por vuelo (ya no uno por predio).
DROP INDEX IF EXISTS public.airci_canopy_results_site_unique;

ALTER TABLE public.airci_canopy_results
  ADD COLUMN IF NOT EXISTS detector_version text,
  ADD COLUMN IF NOT EXISTS source text NOT NULL DEFAULT 'browser',
  ADD COLUMN IF NOT EXISTS status text NOT NULL DEFAULT 'done',
  ADD COLUMN IF NOT EXISTS is_current boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS processing_ms bigint,
  ADD COLUMN IF NOT EXISTS job_id uuid;

DROP INDEX IF EXISTS public.airci_canopy_results_flight_unique;
CREATE UNIQUE INDEX IF NOT EXISTS airci_canopy_results_current_flight_unique
  ON public.airci_canopy_results (flight_id)
  WHERE flight_id IS NOT NULL AND is_current;

-- Compatibilidad con análisis locales antiguos sin flight_id.
DROP INDEX IF EXISTS public.airci_canopy_results_legacy_site_unique;
CREATE UNIQUE INDEX IF NOT EXISTS airci_canopy_results_legacy_site_unique
  ON public.airci_canopy_results (site_id)
  WHERE flight_id IS NULL AND is_current;

CREATE TABLE IF NOT EXISTS public.airci_detect_jobs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  site_id uuid NOT NULL REFERENCES public.airci_sites (id) ON DELETE CASCADE,
  flight_id uuid NOT NULL REFERENCES public.airci_flights (id) ON DELETE CASCADE,
  owner_id uuid NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  status text NOT NULL DEFAULT 'queued'
    CHECK (status IN ('queued', 'processing', 'done', 'error', 'cancelled')),
  progress smallint NOT NULL DEFAULT 0 CHECK (progress BETWEEN 0 AND 100),
  phase text NOT NULL DEFAULT 'En cola',
  detector_mode text NOT NULL DEFAULT 'classical_v1',
  detector_version text,
  options_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  stats_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  result_id uuid REFERENCES public.airci_canopy_results (id) ON DELETE SET NULL,
  estimated_usd double precision NOT NULL DEFAULT 0,
  actual_usd double precision,
  error_message text,
  created_at timestamptz NOT NULL DEFAULT now(),
  started_at timestamptz,
  finished_at timestamptz,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS airci_detect_jobs_owner_idx
  ON public.airci_detect_jobs (owner_id, created_at DESC);
CREATE INDEX IF NOT EXISTS airci_detect_jobs_site_idx
  ON public.airci_detect_jobs (site_id, created_at DESC);
CREATE INDEX IF NOT EXISTS airci_detect_jobs_flight_idx
  ON public.airci_detect_jobs (flight_id, created_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS airci_detect_jobs_one_active_per_flight
  ON public.airci_detect_jobs (flight_id)
  WHERE status IN ('queued', 'processing');

-- Árboles separados: permite 30k+ registros, paginación y consulta por viewport.
CREATE TABLE IF NOT EXISTS public.airci_canopy_trees (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  result_id uuid NOT NULL REFERENCES public.airci_canopy_results (id) ON DELETE CASCADE,
  site_id uuid NOT NULL REFERENCES public.airci_sites (id) ON DELETE CASCADE,
  flight_id uuid NOT NULL REFERENCES public.airci_flights (id) ON DELETE CASCADE,
  owner_id uuid NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  tree_index integer NOT NULL,
  stable_id text,
  row_no integer,
  position_no integer,
  center_lat double precision NOT NULL,
  center_lng double precision NOT NULL,
  area_px double precision,
  area_m2 double precision,
  diameter_m double precision,
  confidence double precision,
  color_score double precision,
  sem_key text,
  polygon_json jsonb,
  is_deleted boolean NOT NULL DEFAULT false,
  is_manual boolean NOT NULL DEFAULT false,
  metrics_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (result_id, tree_index)
);

CREATE INDEX IF NOT EXISTS airci_canopy_trees_result_idx
  ON public.airci_canopy_trees (result_id, tree_index);
CREATE INDEX IF NOT EXISTS airci_canopy_trees_flight_idx
  ON public.airci_canopy_trees (flight_id, tree_index);
CREATE INDEX IF NOT EXISTS airci_canopy_trees_viewport_idx
  ON public.airci_canopy_trees (result_id, center_lat, center_lng);

ALTER TABLE public.airci_canopy_trees
  ADD COLUMN IF NOT EXISTS is_deleted boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS is_manual boolean NOT NULL DEFAULT false;

-- Diez copas ajustadas por el usuario para calibrar cada vuelo.
CREATE TABLE IF NOT EXISTS public.airci_canopy_calibrations (
  flight_id uuid PRIMARY KEY REFERENCES public.airci_flights (id) ON DELETE CASCADE,
  site_id uuid NOT NULL REFERENCES public.airci_sites (id) ON DELETE CASCADE,
  owner_id uuid NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  calibration_json jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS airci_canopy_calibrations_owner_idx
  ON public.airci_canopy_calibrations (owner_id, updated_at DESC);

ALTER TABLE public.airci_detect_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.airci_canopy_trees ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.airci_canopy_calibrations ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "airci_detect_jobs_admin_all" ON public.airci_detect_jobs;
CREATE POLICY "airci_detect_jobs_admin_all"
  ON public.airci_detect_jobs FOR ALL
  TO authenticated
  USING (public.is_admin_user())
  WITH CHECK (public.is_admin_user());

DROP POLICY IF EXISTS "airci_canopy_trees_admin_all" ON public.airci_canopy_trees;
CREATE POLICY "airci_canopy_trees_admin_all"
  ON public.airci_canopy_trees FOR ALL
  TO authenticated
  USING (public.is_admin_user())
  WITH CHECK (public.is_admin_user());

DROP POLICY IF EXISTS "airci_canopy_calibrations_admin_all" ON public.airci_canopy_calibrations;
CREATE POLICY "airci_canopy_calibrations_admin_all"
  ON public.airci_canopy_calibrations FOR ALL
  TO authenticated
  USING (public.is_admin_user())
  WITH CHECK (public.is_admin_user());

COMMENT ON TABLE public.airci_detect_jobs IS
  'AirCI: cola y progreso de análisis profesional por vuelo.';
COMMENT ON TABLE public.airci_canopy_trees IS
  'AirCI: una fila por árbol/copa para resultados grandes y consultas por viewport.';
COMMENT ON TABLE public.airci_canopy_calibrations IS
  'AirCI: diez copas de referencia y perfil derivado por vuelo.';

-- Promoción atómica: el resultado anterior sigue vigente hasta que el nuevo
-- tenga todos sus árboles guardados.
CREATE OR REPLACE FUNCTION public.airci_promote_canopy_result(p_result_id uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_flight_id uuid;
BEGIN
  SELECT flight_id
    INTO v_flight_id
  FROM public.airci_canopy_results
  WHERE id = p_result_id;

  IF v_flight_id IS NULL THEN
    RAISE EXCEPTION 'Resultado AirCI inválido o sin flight_id';
  END IF;

  UPDATE public.airci_canopy_results
     SET is_current = false,
         updated_at = now()
   WHERE flight_id = v_flight_id
     AND id <> p_result_id
     AND is_current;

  UPDATE public.airci_canopy_results
     SET is_current = true,
         updated_at = now()
   WHERE id = p_result_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Resultado AirCI no encontrado';
  END IF;
END;
$$;

REVOKE ALL ON FUNCTION public.airci_promote_canopy_result(uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.airci_promote_canopy_result(uuid) FROM anon;
REVOKE ALL ON FUNCTION public.airci_promote_canopy_result(uuid) FROM authenticated;
GRANT EXECUTE ON FUNCTION public.airci_promote_canopy_result(uuid) TO service_role;

-- Recalcula los indicadores del lote tras una corrección manual de una copa.
-- Se ejecuta desde la función Netlify con service_role; no se expone al navegador.
CREATE OR REPLACE FUNCTION public.airci_recalculate_canopy_result(p_result_id uuid)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_stats jsonb;
  v_gsd_m double precision;
  v_total_px double precision;
  v_ortho_m2 double precision;
  v_count integer;
  v_sum_px double precision;
  v_mean_px double precision;
  v_std_px double precision;
  v_min_px double precision;
  v_max_px double precision;
  v_cover_pct double precision;
BEGIN
  SELECT stats_json
    INTO v_stats
  FROM public.airci_canopy_results
  WHERE id = p_result_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Resultado AirCI no encontrado';
  END IF;

  v_gsd_m := NULLIF(v_stats->>'gsdM', '')::double precision;
  v_total_px := COALESCE(
    NULLIF(v_stats->>'totalPixels', '')::double precision,
    NULLIF(v_stats->>'widthPx', '')::double precision
      * NULLIF(v_stats->>'heightPx', '')::double precision
  );

  SELECT
    COUNT(*)::integer,
    COALESCE(SUM(area_px), 0),
    COALESCE(AVG(area_px), 0),
    COALESCE(STDDEV_POP(area_px), 0),
    COALESCE(MIN(area_px), 0),
    COALESCE(MAX(area_px), 0)
  INTO v_count, v_sum_px, v_mean_px, v_std_px, v_min_px, v_max_px
  FROM public.airci_canopy_trees
  WHERE result_id = p_result_id
    AND is_deleted = false;

  UPDATE public.airci_canopy_trees AS tree
     SET sem_key = CASE
          WHEN v_std_px <= 1e-9 THEN 'verde'
          WHEN (tree.area_px - v_mean_px) / v_std_px < -1.1 THEN 'rojo'
          WHEN (tree.area_px - v_mean_px) / v_std_px < -0.45 THEN 'amarillo'
          WHEN (tree.area_px - v_mean_px) / v_std_px > 1.0 THEN 'azul'
          ELSE 'verde'
        END,
        metrics_json = COALESCE(tree.metrics_json, '{}'::jsonb)
          || jsonb_build_object(
            'z',
            CASE
              WHEN v_std_px <= 1e-9 THEN 0
              ELSE round(((tree.area_px - v_mean_px) / v_std_px)::numeric, 4)
            END,
            'recalculated_at',
            now()
          )
   WHERE tree.result_id = p_result_id
     AND tree.is_deleted = false;

  v_cover_pct := CASE
    WHEN v_total_px > 0 THEN LEAST(100, 100 * v_sum_px / v_total_px)
    ELSE 0
  END;
  v_ortho_m2 := CASE
    WHEN v_gsd_m > 0 AND v_total_px > 0 THEN v_total_px * v_gsd_m * v_gsd_m
    ELSE NULL
  END;

  v_stats := COALESCE(v_stats, '{}'::jsonb) || jsonb_build_object(
    'count', v_count,
    'coverPct', round(v_cover_pct::numeric, 3),
    'barePct', round((100 - v_cover_pct)::numeric, 3),
    'meanArea', round(v_mean_px::numeric, 3),
    'stdArea', round(v_std_px::numeric, 3),
    'minArea', round(v_min_px::numeric, 3),
    'maxArea', round(v_max_px::numeric, 3),
    'cvPct', CASE WHEN v_mean_px > 0 THEN round((100 * v_std_px / v_mean_px)::numeric, 3) ELSE 0 END,
    'maxVsMeanPct', CASE WHEN v_mean_px > 0 THEN round((100 * (v_max_px - v_mean_px) / v_mean_px)::numeric, 3) ELSE 0 END,
    'minVsMeanPct', CASE WHEN v_mean_px > 0 THEN round((100 * (v_min_px - v_mean_px) / v_mean_px)::numeric, 3) ELSE 0 END,
    'maxMinRatio', CASE WHEN v_min_px > 0 THEN round((v_max_px / v_min_px)::numeric, 4) ELSE NULL END,
    'vegPixels', round(v_sum_px::numeric, 3),
    'canopyAreaM2', CASE WHEN v_gsd_m > 0 THEN round((v_sum_px * v_gsd_m * v_gsd_m)::numeric, 3) ELSE NULL END,
    'meanAreaM2', CASE WHEN v_gsd_m > 0 THEN round((v_mean_px * v_gsd_m * v_gsd_m)::numeric, 3) ELSE NULL END,
    'minAreaM2', CASE WHEN v_gsd_m > 0 THEN round((v_min_px * v_gsd_m * v_gsd_m)::numeric, 3) ELSE NULL END,
    'maxAreaM2', CASE WHEN v_gsd_m > 0 THEN round((v_max_px * v_gsd_m * v_gsd_m)::numeric, 3) ELSE NULL END,
    'orthoAreaM2', v_ortho_m2,
    'orthoAreaHa', CASE WHEN v_ortho_m2 IS NOT NULL THEN v_ortho_m2 / 10000 ELSE NULL END,
    'bareAreaM2', CASE WHEN v_ortho_m2 IS NOT NULL THEN GREATEST(0, v_ortho_m2 - v_sum_px * v_gsd_m * v_gsd_m) ELSE NULL END,
    'treesPerHa', CASE WHEN v_ortho_m2 > 0 THEN v_count * 10000 / v_ortho_m2 ELSE NULL END,
    'manualEditsRecalculatedAt', now()
  );

  UPDATE public.airci_canopy_results
     SET tree_count = v_count,
         cover_pct = v_cover_pct,
         mean_area_px = v_mean_px,
         std_area_px = v_std_px,
         stats_json = v_stats,
         updated_at = now()
   WHERE id = p_result_id;

  RETURN v_stats;
END;
$$;

REVOKE ALL ON FUNCTION public.airci_recalculate_canopy_result(uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.airci_recalculate_canopy_result(uuid) FROM anon;
REVOKE ALL ON FUNCTION public.airci_recalculate_canopy_result(uuid) FROM authenticated;
GRANT EXECUTE ON FUNCTION public.airci_recalculate_canopy_result(uuid) TO service_role;
