-- =============================================================================
-- AirCI Professional — trabajos asíncronos + resultados por vuelo + árboles
-- =============================================================================
-- Ejecutar en Supabase SQL Editor después de:
--   1) supabase-airci.sql
--   2) supabase-airci-canopy-results.sql
--
-- Es idempotente. Conserva los resultados legacy en trees_json.
-- =============================================================================

-- Un resultado por vuelo (ya no uno por predio).
DROP INDEX IF EXISTS public.airci_canopy_results_site_unique;

ALTER TABLE public.airci_canopy_results
  ADD COLUMN IF NOT EXISTS detector_version text,
  ADD COLUMN IF NOT EXISTS source text NOT NULL DEFAULT 'browser',
  ADD COLUMN IF NOT EXISTS status text NOT NULL DEFAULT 'done',
  ADD COLUMN IF NOT EXISTS is_current boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS processing_ms bigint,
  ADD COLUMN IF NOT EXISTS job_id uuid;

DROP INDEX IF EXISTS public.airci_canopy_results_flight_unique;
CREATE UNIQUE INDEX IF NOT EXISTS airci_canopy_results_current_flight_unique
  ON public.airci_canopy_results (flight_id)
  WHERE flight_id IS NOT NULL AND is_current;

-- Compatibilidad con análisis locales antiguos sin flight_id.
DROP INDEX IF EXISTS public.airci_canopy_results_legacy_site_unique;
CREATE UNIQUE INDEX IF NOT EXISTS airci_canopy_results_legacy_site_unique
  ON public.airci_canopy_results (site_id)
  WHERE flight_id IS NULL AND is_current;

CREATE TABLE IF NOT EXISTS public.airci_detect_jobs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  site_id uuid NOT NULL REFERENCES public.airci_sites (id) ON DELETE CASCADE,
  flight_id uuid NOT NULL REFERENCES public.airci_flights (id) ON DELETE CASCADE,
  owner_id uuid NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  status text NOT NULL DEFAULT 'queued'
    CHECK (status IN ('queued', 'processing', 'done', 'error', 'cancelled')),
  progress smallint NOT NULL DEFAULT 0 CHECK (progress BETWEEN 0 AND 100),
  phase text NOT NULL DEFAULT 'En cola',
  detector_mode text NOT NULL DEFAULT 'classical_v1',
  detector_version text,
  options_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  stats_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  result_id uuid REFERENCES public.airci_canopy_results (id) ON DELETE SET NULL,
  estimated_usd double precision NOT NULL DEFAULT 0,
  actual_usd double precision,
  error_message text,
  created_at timestamptz NOT NULL DEFAULT now(),
  started_at timestamptz,
  finished_at timestamptz,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS airci_detect_jobs_owner_idx
  ON public.airci_detect_jobs (owner_id, created_at DESC);
CREATE INDEX IF NOT EXISTS airci_detect_jobs_site_idx
  ON public.airci_detect_jobs (site_id, created_at DESC);
CREATE INDEX IF NOT EXISTS airci_detect_jobs_flight_idx
  ON public.airci_detect_jobs (flight_id, created_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS airci_detect_jobs_one_active_per_flight
  ON public.airci_detect_jobs (flight_id)
  WHERE status IN ('queued', 'processing');

-- Árboles separados: permite 30k+ registros, paginación y consulta por viewport.
CREATE TABLE IF NOT EXISTS public.airci_canopy_trees (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  result_id uuid NOT NULL REFERENCES public.airci_canopy_results (id) ON DELETE CASCADE,
  site_id uuid NOT NULL REFERENCES public.airci_sites (id) ON DELETE CASCADE,
  flight_id uuid NOT NULL REFERENCES public.airci_flights (id) ON DELETE CASCADE,
  owner_id uuid NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  tree_index integer NOT NULL,
  stable_id text,
  row_no integer,
  position_no integer,
  center_lat double precision NOT NULL,
  center_lng double precision NOT NULL,
  area_px double precision,
  area_m2 double precision,
  diameter_m double precision,
  confidence double precision,
  color_score double precision,
  sem_key text,
  polygon_json jsonb,
  metrics_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (result_id, tree_index)
);

CREATE INDEX IF NOT EXISTS airci_canopy_trees_result_idx
  ON public.airci_canopy_trees (result_id, tree_index);
CREATE INDEX IF NOT EXISTS airci_canopy_trees_flight_idx
  ON public.airci_canopy_trees (flight_id, tree_index);
CREATE INDEX IF NOT EXISTS airci_canopy_trees_viewport_idx
  ON public.airci_canopy_trees (result_id, center_lat, center_lng);

ALTER TABLE public.airci_detect_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.airci_canopy_trees ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "airci_detect_jobs_admin_all" ON public.airci_detect_jobs;
CREATE POLICY "airci_detect_jobs_admin_all"
  ON public.airci_detect_jobs FOR ALL
  TO authenticated
  USING (public.is_admin_user())
  WITH CHECK (public.is_admin_user());

DROP POLICY IF EXISTS "airci_canopy_trees_admin_all" ON public.airci_canopy_trees;
CREATE POLICY "airci_canopy_trees_admin_all"
  ON public.airci_canopy_trees FOR ALL
  TO authenticated
  USING (public.is_admin_user())
  WITH CHECK (public.is_admin_user());

COMMENT ON TABLE public.airci_detect_jobs IS
  'AirCI: cola y progreso de análisis profesional por vuelo.';
COMMENT ON TABLE public.airci_canopy_trees IS
  'AirCI: una fila por árbol/copa para resultados grandes y consultas por viewport.';

-- Promoción atómica: el resultado anterior sigue vigente hasta que el nuevo
-- tenga todos sus árboles guardados.
CREATE OR REPLACE FUNCTION public.airci_promote_canopy_result(p_result_id uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_flight_id uuid;
BEGIN
  SELECT flight_id
    INTO v_flight_id
  FROM public.airci_canopy_results
  WHERE id = p_result_id;

  IF v_flight_id IS NULL THEN
    RAISE EXCEPTION 'Resultado AirCI inválido o sin flight_id';
  END IF;

  UPDATE public.airci_canopy_results
     SET is_current = false,
         updated_at = now()
   WHERE flight_id = v_flight_id
     AND id <> p_result_id
     AND is_current;

  UPDATE public.airci_canopy_results
     SET is_current = true,
         updated_at = now()
   WHERE id = p_result_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Resultado AirCI no encontrado';
  END IF;
END;
$$;

REVOKE ALL ON FUNCTION public.airci_promote_canopy_result(uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.airci_promote_canopy_result(uuid) FROM anon;
REVOKE ALL ON FUNCTION public.airci_promote_canopy_result(uuid) FROM authenticated;
GRANT EXECUTE ON FUNCTION public.airci_promote_canopy_result(uuid) TO service_role;
